apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: 03-approve-pants
  namespace: tenant-01  # If shared tenant must be correct NS
spec:
  path: ../tf-resources
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: tf-controller-demo
    namespace: flux-system
  storeReadablePlan: human
  ###
  approvePlan: ""
