apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenant-secrets
spec:
  targetNamespace: tenant-01
  interval: 15s
  decryption:
    provider: sops
    secretRef:
      name: tenant-sops-gpg
  sourceRef:
    kind: GitRepository
    name: tf-controller-demo
    namespace: flux-system
  path: "./09-hello-lamp-from-sops"
  prune: true
