apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: 09-hello-lamp-from-sops
  namespace: tenant-01  

spec:
  path: ../tf-resources
  interval: 10s
  sourceRef:
    kind: GitRepository
    name: tf-controller-demo
    namespace: flux-system
  storeReadablePlan: human
  approvePlan: "auto"
  writeOutputsToSecret:
    name: 09-hello-lamp-from-sops
  alwaysCleanupRunnerPod: false
  ### Pass variables to Terrafrom
  varsFrom:
  - kind: Secret
    name: tf-sops-lamps
    varsKeys:
    - subject 

# Display outputs
# kubectl -n tenant-01 get secret 09-hello-lamp-from-sops   -ojsonpath='{.data.hello_world}' | base64 -d 

# Generate secret
# kubectl -n tenant-01 create secret generic tf-sops-lamps --from-literal=subject=my-sops-lamp  --from-literal=your-subject=your-sops-lamp   --dry-run -o yaml > tf-sops-lamp.yaml
# sops --encrypt --in-place tf-sops-lamp.yaml



# varsFrom:
#   description: List of references to a Secret or a ConfigMap to generate
#     variables for Terraform resources based on its data, selectively
#     by varsKey. Values of the later Secret / ConfigMap with the same
#     keys will override those of the former.
#   items:
#     description: VarsReference contain a reference of a Secret or a
#       ConfigMap to generate variables for Terraform resources based
#       on its data, selectively by varsKey.
#     properties:
#       kind:
#         description: Kind of the values referent, valid values are ('Secret',
#           'ConfigMap').
#         enum:
#         - Secret
#         - ConfigMap
#         type: string
#       name:
#         description: Name of the values referent. Should reside in the
#           same namespace as the referring resource.
#         maxLength: 253
#         minLength: 1
#         type: string
#       optional:
#         description: Optional marks this VarsReference as optional.
#           When set, a not found error for the values reference is ignored,
#           but any VarsKey or transient error will still result in a
#           reconciliation failure.
#         type: boolean
#       varsKeys:
#         description: VarsKeys is the data key at which a specific value
#           can be found. Defaults to all keys.
#         items:
#           type: string
#         type: array
#     required:
#     - kind
#     - name
#     type: object
#   type: array

