apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: hello-lamp
  namespace: tenant-01  # If shared tenant must be correct NS
spec:
  path: ./05-hello-lamp
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: tf-controller-demo
    namespace: flux-system
  writeOutputsToSecret:
    name: tf-output-lamp
  alwaysCleanupRunnerPod: false 
  vars:
  - name: subject  
    value: lamped
